# Generated by Django 3.0.8 on 2020-12-23 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productType',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
