# Generated by Django 3.0.8 on 2020-12-26 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20201224_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='large',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='medium',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='small',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
