# Generated by Django 3.0.8 on 2021-02-08 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_productcomment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductComment',
            new_name='Comment',
        ),
    ]
