# Generated by Django 3.0.8 on 2021-02-24 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_auto_20210222_1952'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('1', 'Small'), ('2', 'Medium'), ('3', 'Large')], max_length=120)),
            ],
        ),
    ]
