# Generated by Django 3.0.8 on 2021-02-24 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_size'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Size',
        ),
    ]
